// ============================================================================
// ENUMS - System Constants
// ============================================================================

/**
 * RF-01: User Roles
 * Defines all system roles with their unique identifiers
 * CONSTRAINT: A user can have only one role
 */
export enum UserRole {
  ADMIN = 1,                    // System Administrator - Full access
  PLANNING = 2,                 // Planning Manager - Project/Folio management
  SECTION_CHIEF = 3,            // Section Manager - Section-level operations
  OPERATOR = 4,                 // Process Operator - Process execution
  SALESMAN = 5,                 // Sales - Client/project sales
  MANAGER = 6                   // Executive/Management - Reporting
}

/**
 * Role names for database seeding and audit logs
 */
export const RoleNames: Record<UserRole, string> = {
  [UserRole.ADMIN]: "ADMIN",
  [UserRole.PLANNING]: "PLANNING",
  [UserRole.SECTION_CHIEF]: "SECTION_CHIEF",
  [UserRole.OPERATOR]: "OPERATOR",
  [UserRole.SALESMAN]: "SALESMAN",
  [UserRole.MANAGER]: "MANAGER"
};

export enum ProcessType {
  POR_CANTIDAD = "POR_CANTIDAD",
  UNITARIO = "UNITARIO"
}

export enum ProcessStatus {
  NOT_STARTED = "NOT_STARTED",
  IN_PROGRESS = "IN_PROGRESS",
  PAUSED = "PAUSED",
  COMPLETED = "COMPLETED"
}

export enum FolioStatus {
  ACTIVE = "ACTIVE",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED"
}

export enum GarmentStatus {
  PENDING = "PENDING",
  IN_PROGRESS = "IN_PROGRESS",
  COMPLETED = "COMPLETED"
}

export enum FolioRouteStatus {
  NOT_STARTED = "NOT_STARTED",
  IN_PROGRESS = "IN_PROGRESS",
  COMPLETED = "COMPLETED"
}

export enum AuditAction {
  STATE_CHANGE = "STATE_CHANGE",
  PROGRESS_UPDATE = "PROGRESS_UPDATE",
  DATE_CHANGE = "DATE_CHANGE",
  CREATED = "CREATED",
  UPDATED = "UPDATED",
  DELETED = "DELETED"
}

// ============================================================================
// DOMAIN MODELS - RF-01 Compliant
// ============================================================================

/**
 * RF-01: Role Entity
 * Represents a system role stored in the database
 * Provides the foundation for RBAC (Role-Based Access Control)
 *
 * CONSTRAINT: Roles are system-defined and immutable
 */
export interface Role {
  id: UserRole;               // PK: Maps to UserRole enum
  name: string;               // UNIQUE: Role identifier (e.g., "ADMIN")
  description: string | null; // Purpose and permissions of the role
  is_active: boolean;         // Whether role accepts new user assignments
  created_at: Date;           // Timestamp of creation
}

/**
 * RF-01: Section Entity
 * Represents an organizational unit within production
 * Users can belong to at most one section
 *
 * CONSTRAINT: section_id in users table is NULLABLE (user can work outside any section)
 */
export interface Section {
  id: number;                 // PK: Auto-increment
  name: string;               // UNIQUE: Section identifier (e.g., "Corte", "Costura")
  description: string | null; // Details about the section
  is_active: boolean;         // Whether section accepts new workers
  created_at: Date;           // Timestamp of creation
  updated_at: Date;           // Timestamp of last change
}

/**
 * RF-01: User Entity (Complete Domain Model)
 * 
 * CONSTRAINTS:
 * 1. email must be UNIQUE (no duplicate accounts)
 * 2. password_hash must never be null (all users have passwords)
 * 3. role_id is NOT NULL - every user has exactly one role
 * 4. section_id is NULLABLE - user may work outside a section (e.g., Admin, Sales)
 * 5. is_active controls access (soft delete pattern)
 *
 * SECURITY:
 * - password_hash is generated by bcryptjs.hash() with salt rounds = 10
 * - Raw passwords are never stored or logged
 * - Password comparison uses bcryptjs.compare() with constant-time algorithm
 */
export interface User {
  id: number;                  // PK: Auto-increment user ID
  email: string;               // UNIQUE: User login identifier
  password_hash: string;       // Bcrypt hash of user password (never raw password)
  full_name: string;           // User display name
  role_id: UserRole;           // FK to roles table - CANNOT BE NULL
  section_id: number | null;   // FK to sections table - NULLABLE (optional)
  is_active: boolean;          // Whether user can authenticate
  created_at: Date;            // Account creation timestamp
  updated_at: Date;            // Last modification timestamp
}

/**
 * RF-01: User with Role Details (Authorization Context)
 * Enhanced user model that includes role information
 * Used by authorization middleware and services
 *
 * USAGE: After JWT validation, enrich user context with role details
 */
export interface UserWithRole extends User {
  role: Role;                  // Full role object for permission checks
}

/**
 * RF-01: Authorization Payload (JWT Claim)
 * Minimal information needed for stateless authentication
 * Included in JWT token to avoid DB lookups on every request
 *
 * NOTE: We store role_id (number) to keep payload small
 * Role name can be looked up when needed for complex authorization
 */
export interface AuthPayload {
  id: number;                  // User ID
  email: string;               // User email (for audit/debugging)
  role_id: UserRole;           // User's single role
  section_id: number | null;   // User's optional section
}

export interface Folio {
  id: number;
  folio_number: string;
  project_id: number;
  quantity: number;
  status: FolioStatus;
  created_at: Date;
  updated_at: Date;
}

export interface Garment {
  id: number;
  folio_id: number;
  garment_number: number;
  garment_code: string;
  status: GarmentStatus;
  created_at: Date;
  updated_at: Date;
}

export interface Client {
  id: number;
  name: string;
  contact_email: string | null;
  phone: string | null;
  address: string | null;
  is_active: boolean;
  created_at: Date;
  updated_at: Date;
}

export interface Project {
  id: number;
  name: string;
  client_id: number;
  salesman_id: number;
  description: string | null;
  is_active: boolean;
  created_at: Date;
  updated_at: Date;
}

export interface Route {
  id: number;
  name: string;
  description: string | null;
  is_active: boolean;
  created_at: Date;
  updated_at: Date;
}

export interface RouteSection {
  id: number;
  route_id: number;
  section_id: number;
  sequence_order: number;
  is_active: boolean;
  created_at: Date;
}

export interface Process {
  id: number;
  section_id: number;
  name: string;
  description: string | null;
  type: ProcessType;
  is_active: boolean;
  created_at: Date;
  updated_at: Date;
}

export interface FolioRoute {
  id: number;
  folio_id: number;
  route_id: number;
  current_route_section_id: number | null;
  status: FolioRouteStatus;
  started_at: Date | null;
  completed_at: Date | null;
  created_at: Date;
  updated_at: Date;
}

export interface FolioProcess {
  id: number;
  folio_id: number;
  garment_id: number;
  process_id: number;
  route_section_id: number;
  status: ProcessStatus;
  total_quantity: number;
  completed_quantity: number;
  started_at: Date | null;
  completed_at: Date | null;
  created_at: Date;
  updated_at: Date;
}

export interface ProcessProgress {
  id: number;
  folio_process_id: number;
  quantity_completed: number;
  updated_by_user_id: number;
  reason: string;
  comments: string | null;
  updated_at: Date;
}

export interface DeliveryDate {
  id: number;
  folio_id: number;
  due_date: Date;
  notes: string | null;
  is_active: boolean;
  created_at: Date;
  updated_at: Date;
}

export interface DeliveryDateHistory {
  id: number;
  folio_id: number;
  old_due_date: Date;
  new_due_date: Date;
  changed_by_user_id: number;
  reason: string;
  changed_at: Date;
}

export interface AuditLog {
  id: number;
  action: AuditAction;
  entity_type: string;
  entity_id: number;
  user_id: number;
  old_value: string | null;
  new_value: string | null;
  description: string;
  timestamp: Date;
}
